### ISSUE TITLE
Person_Detector_v4_inferencing.h: No such file or directory

### ISSUE THREAD

**Issue by CazYokoyama** [curso-verano-iot-uah/person-detection-esp32s3#7]
main:5:10: fatal error: Person_Detector_v4_inferencing.h: No such file or directory
 #include <Person_Detector_v4_inferencing.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by msalexms** [comment]
Hi, have you install the model library? [https://github.com/ai4iot/person-detection-esp32s3/blob/main/model-zoo/MobileNetV2-160-91-8int-ino.zip](url)

**Comment by CazYokoyama** [comment]
You are correct. I successfully build when the required libraries are installed. Thx.

**Comment by msalexms** [comment]
Perfect!
